Adding revised nemesis-install

diff --git a/bin/nemesis-install b/bin/nemesis-install
--- a/bin/nemesis-install
+++ b/bin/nemesis-install
@@ -4,48 +4,13 @@
 # (c) 2013 Sam caldwell.  All Rights Reserved.
 #
 set -e
-export PATH=$PATH:/srv/nemesis/bin/
-
 export DEBUG=1
 [ $DEBUG -eq 1 ] && set -x
 
-init_profile(){
-	ln -sf /srv/nemesis/etc/vimrc /root/.vimrc
-	ln -sf /srv/nemesis/etc/nemesis.profile /etc/profile.d/nemesis.sh
-	. /etc/profile
-}
+export PATH=$PATH:/srv/nemesis/bin/
+export BUILD_PATH=/srv/nemesis/src
+export TIME_SERVER="0.pool.ntp.org"
 
-base_install(){
-	#
-	#base installation
-	#
-	init_profile && \
-	ln -sf /srv/nemesis/bin/delay /usr/bin/delay && \
-	echo "Updating the clock..." && \
-	time ntpdate $TIME_SERVER && \
-	echo "installing software packages" && \
-	time apt-get install vim -y && \
-	time apt-get install openssh-server openssh-client -y && \
-	time apt-get install openssl -y && \
-	time apt-get install mongodb && \
-	time apt-get install nginx-full -y && \
-	time /srv/nemesis/src/build-nemesis && \
-	echo "software is now installed...configuring system." && \
-	rm -f /etc/nginx/sites-enabled/* && \
-	rm -rf /etc/nginx/sites-available && \
-	rm -rf /etc/rsyslog* && \
-	ln -sf /srv/nemesis/etc/nginx/sites-available /etc/nginx/sites-available && \
-	ln -sf /srv/nemesis/etc/nginx/sites-available/${SERVER_TYPE} /etc/nginx/sites-enabled/${SERVER_TYPE} && \
-	ln -sf /srv/nemesis/etc/init/${SERVER_TYPE} /etc/init/${SERVER_TYPE} && \
-	ln -sf /srv/nemesis/etc/init.d/nemesis-${SERVER_TYPE} /etc/init.d/nemesis-${SERVER_TYPE} && \
-	ln -sf /srv/nemesis/etc/rsyslog/rsyslog.conf /etc/rsyslog.conf && \
-	service rsyslog restart && \
-	mkdir -p /var/run/nemesis/${SERVER_TYPE} && \
-	mkdir -p /var/log/nemesis/{audit,broker,cipher,keys} && \
-	echo "Base installation complete for ${SERVER_TYPE}" && return 0
-	# Fall through if a failure occurs.
-	echo "base_install() failed for ${SERVER_TYPE}" && return 1
-}
 [ "$(whoami)" != "root" ] && echo "$0 must be run as root." && exit 1
 [ -z "$1" ] && echo "Missing argument." && exit 1
 [ ! -z "$2" ] && {
@@ -55,46 +20,107 @@ base_install(){
 	}
 }
 
-export SERVER_TYPE=$(echo "$1" | tr -dc a-z)
-export TIME_SERVER="0.pool.ntp.org"
+ln -sf /srv/nemesis/etc/vimrc /root/.vimrc && \
+ln -sf /srv/nemesis/etc/nemesis.profile /etc/profile.d/nemesis.sh && \
+. /etc/profile && \
+ln -sf /srv/nemesis/bin/delay /usr/bin/delay && \
+echo "Updating the clock..." && \
+time ntpdate $TIME_SERVER && \
+echo "installing software packages" && \
+time apt-get install vim openssh-server openssh-client openssl \
+					 mongodb nginx-full binutils cpp cpp-4.7 \
+					 g++ g++-4.7 gcc gcc-4.7 fakeroot \
+					 libgcc-4.7-dev make -y && \
+rm -f /etc/nginx/sites-enabled/* && \
+rm -rf /etc/nginx/sites-available && \
+rm -rf /etc/rsyslog* && \
+ln -sf /srv/nemesis/etc/nginx/sites-available /etc/nginx/sites-available && \
+ln -sf /srv/nemesis/etc/nginx/sites-available/${SERVER_TYPE} /etc/nginx/sites-enabled/${SERVER_TYPE} && \
+ln -sf /srv/nemesis/etc/init/${SERVER_TYPE} /etc/init/${SERVER_TYPE} && \
+ln -sf /srv/nemesis/etc/init.d/nemesis-${SERVER_TYPE} /etc/init.d/nemesis-${SERVER_TYPE} && \
+ln -sf /srv/nemesis/etc/rsyslog/rsyslog.conf /etc/rsyslog.conf && \
+service rsyslog restart && \
+mkdir -p /var/run/nemesis/${SERVER_TYPE} && \
+mkdir -p /var/log/nemesis/{audit,broker,cipher,keys} && \
+echo "Base installation complete" || {
+	echo "base_install() failed"
+	return 1
+}
 
-echo "Starting install ( $SERVER_TYPE )..."
+create_default_config(){
+cat > /etc/network/interfaces << EOF_CONFIG
+#/etc/network/interfaces
+#  mail@samcaldwell.net
+#
+auto lo
+iface lo inet loopback
 
-case "$SERVER_TYPE" in 
-	audit)
-		base_install $SERVER_TYPE
-		[ $? -ne 0 ] && echo "One or more errors occurred." && exit 1
-		create-ssl-certificates $SERVER_TYPE
-		configure-network
-		#add more steps here
+auto eth0
+iface eth0 inet dhcp
+#END OF /etc/network/interfaces#
+EOF_CONFIG
+}
+
+
+
+[ "$(whoami)" != "root" ] && echo "This script must run as root." && exit 1
+[ "$(grep DISTRIB_ID /etc/lsb-release | awk -F \= '{print $2}')" != "Ubuntu" ] && {
+	echo "This script will only work with Ubuntu."
+	echo "It would probably work with Debian, but it hasn't been tested."
+	exit 1
+}
+
+echo " "
+[ "$(getYesNo 'Configure networking?')" != "Y" ] && {
+	echo " "
+	echo "You said 'No' (N/n)...terminating."
+	echo " "
+	exit 0
+}
+echo " "
+[ "$(getYesNo 'Set a static IP address?')" != "Y" ] && {
+		echo "Configuring for DHCP"
+		create_default_config
+		echo "restarting network"
+		restart_networking
 		exit 0
-	;;
-	cipher)
-		base_install $SERVER_TYPE
-		[ $? -ne 0 ] && echo "One or more errors occurred." && exit 1
-		create-ssl-certificates $SERVER_TYPE
-		configure-network
-		#add more steps here
-		exit 0
-	;;
-	broker)
-		base_install $SERVER_TYPE
-		[ $? -ne 0 ] && echo "One or more errors occurred." && exit 1
-		create-ssl-certificates $SERVER_TYPE
-		configure-network
-		#add more steps here
-		exit 0
-	;;
-	keys)
-		base_install $SERVER_TYPE
-		[ $? -ne 0 ] && echo "One or more errors occurred." && exit 1
-		create-ssl-certificates $SERVER_TYPE
-		configure-network
-		#add more steps here
-		exit 0
-	;;
-	*)
-		echo "USAGE: $0 [broker,cipher,keys]"
-		exit 1
-	;;
-esac
+}
+echo " " 
+ADDRESS="$(getIP 'Enter IP Address')"
+echo " "
+NETMASK="$(getMask 'Enter Subnet Mask')"
+echo " "
+GATEWAY="$(getIP 'Enter Gateway')"
+echo " "
+DNS="$(getIP 'Enter DNS IP')"
+echo " "
+
+[ "$(getYesNo 'Are these settings correct?')" != "Y" ] && {
+	echo " "
+	echo "Not applying the changes"
+	echo " "
+}
+echo "Setting the following parameters:"
+echo "    proto:   static"
+echo "    address: $ADDRESS"
+echo "    netmask: $NETMASK"
+echo "    gateway: $GATEWAY"
+echo "    dns:     $DNS"
+echo " "
+create_default_config
+
+
+add_static_ip(){
+	sed -i -e 's/dhcp/static/' /etc/network/interfaces
+	echo "address $ADDRESS" >> /etc/network/interfaces
+	echo "netmask $NETMASK" >> /etc/network/interfaces
+	echo "gateway $GATEWAY" >> /etc/network/interfaces
+	echo "dns-nameservers $DNS" >> /etc/network/interfaces
+}
+
+
+echo "Restarting network..."
+/etc/init.d/networking restart &> /dev/null
+[ "$?" != "0" ] && echo "Network failed to restart" && exit 1
+echo "...Network restarted"
+
